--- # ---------------------------------------------------------------------------
# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
OrdererOrgs:
    # ---------------------------------------------------------------------------
    # Orderer
    # ---------------------------------------------------------------------------
    - Name: Orderer
      Domain: example.com
      EnableNodeOUs: false

      # ---------------------------------------------------------------------------
      # "Specs" - See PeerOrgs below for complete description
      # ---------------------------------------------------------------------------
      Specs:
          - Hostname: orderer

# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
    # ---------------------------------------------------------------------------
    # Org1
    # ---------------------------------------------------------------------------
    - Name: Org1
      Domain: org1.example.com
      EnableNodeOUs: false
      Specs:
          - Hostname: org1
      Template:
          Count: 1
      Users:
          Count: 1

    # ---------------------------------------------------------------------------
    # Org2
    # ---------------------------------------------------------------------------
    - Name: Org2
      Domain: org2.example.com
      EnableNodeOUs: false
      Specs:
          - Hostname: org2
      Template:
          Count: 1
      Users:
          Count: 1
    # ---------------------------------------------------------------------------
    # Org3
    # ---------------------------------------------------------------------------

    - Name: Org3
      Domain: org3.example.com
      EnableNodeOUs: false
      Specs:
          - Hostname: org3
      Template:
          Count: 1
      Users:
          Count: 1
